# Generated by Django 2.0.2 on 2018-02-28 04:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Corps',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default='')),
                ('jurisdiction_code', models.SlugField(default='')),
                ('current_status', models.SlugField(default='')),
                ('company_type', models.CharField(default='Corp', max_length=10)),
                ('opencorporates_url', models.URLField(default='')),
                ('alternative_names', models.TextField(default='')),
                ('registered_address_in_full', models.TextField(default='')),
                ('registry_url', models.URLField(default='')),
                ('company_number', models.CharField(default='N/A', max_length=10)),
                ('controlling_entity', models.TextField(default='')),
                ('ultimate_beneficial_owners', models.TextField(default='')),
                ('officers', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Lawmaker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('corps', models.ManyToManyField(to='legislator.Corps', verbose_name='list of corporations')),
            ],
        ),
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('abbr', models.CharField(max_length=2)),
                ('industries', models.ManyToManyField(to='legislator.Industry')),
            ],
        ),
        migrations.AddField(
            model_name='lawmaker',
            name='party',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='legislator.Party'),
        ),
        migrations.AddField(
            model_name='lawmaker',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='legislator.State', verbose_name="the lawmaker's state"),
        ),
        migrations.AddField(
            model_name='corps',
            name='industry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='legislator.Industry'),
        ),
    ]
