# Generated by Django 2.0.2 on 2018-03-05 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legislator', '0003_auto_20180304_2123'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialinterest',
            name='made_api_call',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='opencorps',
            name='inactive',
            field=models.BooleanField(default=False),
        ),
    ]
