# Generated by Django 2.0.2 on 2018-03-05 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legislator', '0004_auto_20180304_2216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opencorps',
            name='inactive',
            field=models.NullBooleanField(default=False),
        ),
    ]
