.separator "|"
.import ak_legislators.csv ak
.import al_legislators.csv al
.import ar_legislators.csv ar
.import az_legislators.csv az
.import ca_legislators.csv ca
.import co_legislators.csv co
.import ct_legislators.csv ct
.import dc_legislators.csv dc
.import de_legislators.csv de
.import fl_legislators.csv fl
.import ga_legislators.csv ga
.import hi_legislators.csv hi
.import ia_legislators.csv ia
.import id_legislators.csv id
.import il_legislators.csv il
.import in_legislators.csv in
.import ks_legislators.csv ks
.import ky_legislators.csv ky
.import la_legislators.csv la
.import ma_legislators.csv ma
.import md_legislators.csv md
.import me_legislators.csv me
.import mi_legislators.csv mi
.import mn_legislators.csv mn
.import mo_legislators.csv mo
.import ms_legislators.csv ms
.import mt_legislators.csv mt
.import nc_legislators.csv nc
.import nd_legislators.csv nd
.import ne_legislators.csv ne
.import nh_legislators.csv nh
.import nj_legislators.csv nj
.import nm_legislators.csv nm
.import nv_legislators.csv nv
.import ny_legislators.csv ny
.import oh_legislators.csv oh
.import ok_legislators.csv ok
.import or_legislators.csv or
.import pa_legislators.csv pa
.import pr_legislators.csv pr
.import ri_legislators.csv ri
.import sc_legislators.csv sc
.import sd_legislators.csv sd
.import tn_legislators.csv tn
.import tx_legislators.csv tx
.import ut_legislators.csv ut
.import va_legislators.csv va
.import vt_legislators.csv vt
.import wa_legislators.csv wa
.import wi_legislators.csv wi
.import wv_legislators.csv wv
.import wy_legislators.csv wy
