import requests
import json
import urllib
from django.db import models
from dotenv import get_key, find_dotenv
from legislator.models import Lawmaker, FinancialInterest, OpenCorps

open_corp_key = get_key(find_dotenv(), "OPEN_CORP_KEY")
open_corp_key = "api_token=" + open_corp_key

def get_company_numbers(name, state):
    ''' Takes the name of an entity (an employer or business interest of a
    legislator) and the state of a legislator. Calls the OpenCorporates
    Company Name Search API with the name of the company and collects all the
    company numbers of entities that may potentially match the employer /
    business interest. If there are multiple positive name matches, filters out
    entities which are located in a different state that the lawmaker, or that
    are inactive.
    '''
    juris_code = "us_" + state.lower()
    company_numbers = []
    company_name = name.replace(" ", "+")
    incorp_filter = "&incorporation\date=:2016-01-01"
    s = company_name + incorp_filter + "&" + open_corp_key
    search_url = "https://api.opencorporates.com/v0.4/companies/search?q=" + s
    response = requests.get(search_url)
    # collect company numbers that may match the business / employer interest
    if response.status_code == 200:
        result = json.loads(response.content)
        for entity in result["results"]["companies"]:
            # if there are multiple name matches, filter on state / status
            if len(result["results"]["companies"]) > 1 and entity["company"]["jurisdiction_code"] != juris_code:
                pass
            elif len(result["results"]["companies"]) > 1 and entity["company"]["inactive"]:
                pass
            else:
                num = entity["company"]["jurisdiction_code"] + "/" + entity["company"]["company_number"]
                company_numbers.append(num)
    elif response.status_code == 401:
        print("Token Incorrect")
    else:
        print("Status code error #: ", response.status_code) # for debugging
    return company_numbers

def get_open_corps(company_numbers):
    ''' Takes the list of company numbers generated by get_company_numbers
    and calls the OpenCorp API Company Search to get information on each of
    the entities. Returns a list of JSON dictionaries, each dictionary
    corresponding to one entity.
    ''' 

    company_list = []
    # for each company number, call the OpenCorp API and collect the info dict
    # that corresponds to that number
    if company_numbers is None:
        pass
    else:
        for number in company_numbers:
            s = number + "?" + open_corp_key
            search_url = "https://api.opencorporates.com/v0.4/companies/" + s
            response = requests.get(search_url)
            if response.status_code == 200:
                result = json.loads(response.content)
                company_list.append(result["results"]["company"])
            else:
                print("Status code error", response.status_code)
    return company_list
